# Generated by Django 4.1.7 on 2023-03-14 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_companyinfo_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinfo',
            name='location_map',
        ),
    ]
